set nocp
scriptencoding utf-8
set encoding=utf-8

filetype plugin on
filetype indent on

runtime macros/matchit.vim


" Map leader key to comma
let mapleader=","

set hidden " Allow unsaved buffers
set foldenable "enable folding

" space open/closes folds
nnoremap <space> za
set foldlevelstart=99 " Dont start new buffers folded
set foldmethod=indent

autocmd FileType vim setlocal foldmethod=marker

"{{{ tabs and spaces

set bs=indent,eol,start " Allow backspacing over everything in insert mode
set tabstop=4 " Tab indentation levels every four columns
set softtabstop=4
set expandtab "Convert all tabs that are typed to spaces
set shiftround "Always indent/outdent to nearest tabstop
set shiftwidth=4 "indent/outdent by four columns
set smarttab "Use shiftwidths at left margin, tabstops everywhere else

set nrformats-=octal

set autoindent 
set smartindent

syntax enable
syntax sync minlines=10000 " Enable syntax for large files
" <leader>fs will redo the syntax for the file
nnoremap <leader>fs :syntax sync minlines=10000<CR>

"wrapping of lines
set colorcolumn=100
set textwidth=100
set wrap
"when wrapping is used, use +++ to denote the break lines
let &showbreak = '+++ '
"make tab in visual mode indent code
vnoremap <tab> >gv
vnoremap <s-tab> <gv

"}}}

"{{{ colors and display
" enable 256 colors
set t_Co=256
set background=dark

color PaperColor
set number
set ruler
set scrolloff=1
set sidescrolloff=5
set display+=lastline
set highlight+=N:DiffText " Make current line number stand out a little
set highlight+=c:LineNr " Blend vertical separators with line numbers

" Make the completion popup look menu-is on a Mac
highlight Pmenu ctermbg=white ctermfg=black
highlight PmenuSel ctermbg=blue ctermfg=white cterm=bold
highlight PmenuSbar ctermbg=grey ctermfg=grey
highlight PmenuThumb ctermbg=blue ctermfg=blue
highlight Folded ctermfg=cyan ctermbg=black

set showcmd " show command in bottom bar

au BufENter * setlocal cursorline " Enbale cursor line on active window
au BufLeave * setlocal nocursorline "Suppress cursorline on inactive window
set wildhar=<Tab>
set wildcharm=<C-Z> "from https://vim.fandom.com/wiki/Easier_buffer_switching

set fillchars=vert:┃
set wildmenu " visual autocomplete for command menu
set wildmode=full " show list of completions
" set wildmode=list:longest,full " show list of completions, and complete as
				 " much as possible, then iterate full completions

set lazyredraw " redraw only when needed (for fast macros)

set updatecount=50 "Save buffer every 50 chars typed
set updatetime=5000 "idlenes is 5 sec

set autoread "Automatically load file if changed outside of vi
set autowrite "save file automatically
set showmatch "highlight matching brackets

if &history < 1000
	set history=1000
endif

if &listchars ==# 'eol:$'
	set listchars=tab:>>\ ,trail:.,extends:>,precedes:<,nbsp:.
endif
set list

set sessionoptions-=options
set viewoptions-=options

"}}}


if v:version > 703 || v:version == 703 && has("patch541")
	set formatoptions+=j " Delete comment character when joining commented lines
endif

" {{{ Searching
set incsearch 
set hlsearch
set ignorecase
set smartcase
" turn off search highlight
nnoremap <silent> <leader><space> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
hi Search term=reverse ctermfg=16 ctermbg=239 guifg=Black guibg=Yellow
"}}}



